export const engineeringQuotes = [
  "The best code is the code you never have to debug.",
  "First make it work. Then make it right. Then make it fast.",
  "Programs must be written for people to read.",
  "Simplicity is the soul of efficiency.",
  "Premature optimization is the root of all evil.",
  "Code is like humor. When you have to explain it, it's bad.",
  "Every great system starts with a simple idea.",
  "Good architecture makes change inexpensive.",
  "Make it simple, but significant.",
  "Great software is built one clean commit at a time.",
  "Any fool can write code that a computer can understand.",
  "The only way to learn a new programming language is by writing programs in it.",
  "Talk is cheap. Show me the code.",
  "First, solve the problem. Then, write the code.",
  "The function of good software is to make the complex appear simple.",
  "Simplicity is prerequisite for reliability.",
  "Controlling complexity is the essence of computer programming.",
  "The most dangerous phrase in the language is 'We've always done it this way.'",
  "It works on my machine.",
  "Debugging is twice as hard as writing the code in the first place.",
  "Deleted code is debugged code.",
  "The best error message is the one that never shows up.",
  "Talk is cheap. Show me the commit history.",
  "Perfection is achieved not when there is nothing more to add, but when there is nothing left to take away.",
  "Software is eating the world.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "In theory, theory and practice are the same. In practice, they're not.",
  "There are only two hard things in Computer Science: cache invalidation and naming things.",
  "It's not a bug — it's an undocumented feature.",
  "A ship in port is safe, but that's not what ships are built for.",
  "Simplicity is about subtracting the obvious and adding the meaningful.",
  "Make it work, make it right, make it fast, make it cheap.",
  "Program testing can be used to show the presence of bugs, but never to show their absence.",
  "The most important property of a program is whether it accomplishes the intention of its user.",
  "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.",
  "The purpose of software engineering is to control complexity.",
  "Clean code always looks like it was written by someone who cares.",
  "Don't communicate by sharing memory; share memory by communicating.",
  "The harder the problem, the more interesting the solution.",
  "Code never lies, comments sometimes do.",
  "Programming today is a race between software engineers striving to build bigger and better idiot-proof programs.",
  "When in doubt, iterate.",
  "The best documentation is the code itself.",
  "If you can't explain it simply, you don't understand it well enough.",
  "Fail fast, fail often, fail forward.",
  "Good programmers know what to write. Great ones know what to rewrite and reuse.",
  "A well-defined problem is half solved.",
  "The most powerful tool in a developer's toolkit is the ability to think.",
  "Ship early, ship often.",
  "Complexity is your enemy.",
  "The best investment is in the tools you use every day.",
  "Working software is the primary measure of progress.",
  "An ounce of prevention is worth a pound of cure.",
  "The art of programming is the art of organizing complexity.",
  "Every line of code you write is a line someone else has to maintain.",
  "Technology is best when it brings people together.",
  "The advance of technology is based on making it fit in so that you don't really even notice it.",
  "It has become appallingly obvious that our technology has exceeded our humanity.",
  "The computer was born to solve problems that did not exist before.",
  "The only way to go fast is to go well.",
  "Optimism is an occupational hazard of programming: feedback is the treatment.",
  "What gets measured gets improved.",
  "Quality is not an act, it is a habit.",
  "The only limit to our realization of tomorrow is our doubts of today.",
  "Creativity is intelligence having fun.",
  "The price of excellence is discipline.",
  "An algorithm must be seen to be believed.",
  "The best way to predict the future is to create it.",
  "Learning never exhausts the mind.",
  "The function of leadership is to produce more leaders, not more followers.",
  "In the middle of difficulty lies opportunity.",
  "Strive for progress, not perfection.",
  "The expert in anything was once a beginner.",
  "Code is poetry.",
  "Architecture is about the important stuff. Whatever that is.",
  "It's a long way to the top if you want to rock and roll.",
  "The only true wisdom is in knowing you know nothing.",
  "Knowledge is power. Information is liberating.",
  "The only thing we have to fear is fear itself.",
  "Stay hungry, stay foolish.",
  "Think different.",
  "Simple is better than complex.",
  "Readability counts.",
  "Special cases aren't special enough to break the rules.",
  "Errors should never pass silently.",
  "In the face of ambiguity, refuse the temptation to guess.",
  "There should be one obvious way to do it.",
  "Now is better than never.",
  "Although never is often better than right now.",
  "If the implementation is hard to explain, it's a bad idea.",
  "If the implementation is easy to explain, it may be a good idea.",
  "Namespaces are one honking great idea.",
  "Refactoring is a continuous process.",
  "The best code is no code at all.",
  "Every new version of a dead technology is one step backward.",
  "Data dominates.",
  "Duplication is far cheaper than the wrong abstraction.",
  "The ?><?php programmer's best friend is the debugger.",
  "Programming isn't about what you know.",
  "You don't learn to walk by following rules.",
  "The key to performance is elegance, not battalions of special cases.",
  "All problems in computer science can be solved by another level of indirection.",
  "The key insight is that software is all about managing complexity.",
  "Good design is as little design as possible.",
  "Less is more.",
  "Simplify, then add lightness.",
  "If you can't do it in your head, you can't debug it in your head.",
  "A plan is not the thing itself but rather a way of getting there.",
  "The purpose of abstraction is not to be vague.",
  "We should forget about small efficiencies, say about 97% of the time.",
  "Premature optimization is the root of all evil.",
  "The most important thing in the architecture is the communication.",
  "Code for the maintainer.",
  "Choose boring technology.",
  "The best time to fix code is before it ships.",
  "There are no shortcuts to any place worth going.",
  "Don't repeat yourself.",
  "The only way to do great work is to love what you do.",
  "Innovation distinguishes between a leader and a follower.",
  "Quality means doing it right when no one is looking.",
  "The best error handling is the one that never needs to execute.",
  "Make the common case fast and the rare case correct.",
  "Progress, not perfection.",
  "The best architects are the ones who listen.",
  "Writing code is a creative act.",
  "The joy of coding is in the solving.",
  "Every bug is a learning opportunity.",
  "Write code as if the person maintaining it is a violent psychopath.",
  "The best code is self-documenting.",
  "Don't optimize for the compiler. Optimize for the reader.",
  "The only thing constant in software is change.",
  "Design is not just what it looks like. Design is how it works.",
  "Premature abstraction is worse than premature optimization.",
  "The purpose of learning is growth.",
  "Everything should be made as simple as possible, but not simpler.",
  "Make it work. Make it right. Make it fast. Make it cheap. Pick three.",
  "The best architects are also the best communicators.",
  "The greatest threat to success is not failure but boredom.",
  "Consistency is the true foundation of trust.",
  "The difference between ordinary and extraordinary is that little extra.",
  "Success is not final, failure is not fatal: it is the courage to continue that counts.",
]

export function getRandomQuote(): string {
  return engineeringQuotes[Math.floor(Math.random() * engineeringQuotes.length)]
}
